version: '3.8'

services:
  labelsmith:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DB_URI=postgresql://username:password@db:5432/labelsmith
    volumes:
      - .:/app 
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: labelsmith
    ports:
      - "5436:5432"
    volumes:
      # - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# volumes:
#   db_data:
